route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'gmail'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'gmail'
  email_configs:
    - to: 'kishorkumara03@gmail.com'
      from: 'kishorkumara03@gmail.com'
      smarthost: smtp.gmail.com:587
      auth_username: 'kishorkumara03@gmail.com'
      auth_identity: 'kishorkumara03@gmail.com'
      auth_password: 'wpve hosl pewi gxrp'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
