global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['3.39.223.78:9100']
  - job_name: 'Prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'AlertManager'
    static_configs:
      - targets: ['localhost:9093']
